stages:
  - test
  - integration

lint:
  image: pipelinecomponents/flake8
  stage: test
  script:
    - flake8

unit_tests:
  image: python:3.8-alpine
  stage: test
  before_script:
    - pip install -r requirements.txt
    - apk add git
  script:
    - coverage run -m unittest tests/test_*
    - codecov

integration:
  image: docker:stable
  stage: integration
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev
    - apk add python3 py-pip make git jq curl
    - pip3 install docker-compose
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b master https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - make -C build/docker reset-mocknet-standalone
    - cd ..
  script:
    - make build
    - make smoke
