stages:
  - test
  - integration

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

lint:
  image: pipelinecomponents/flake8
  stage: test
  script:
    - flake8

unit_tests:
  image: docker/compose:alpine-1.25.4
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apk update
    - apk add git make
    - make build
  script:
    - make test-coverage
    - make test-coverage-report

integration:
  image: docker/compose:alpine-1.25.4
  stage: integration
  tags: 
    - thorchain
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
  artifacts:
    when: on_failure
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./logs/
  before_script:
    - apk update
    - apk add git make
    - (git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/midgard.git && cd midgard && make docker-gitlab-build && cd ..) || true
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b master https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - make -C build/docker reset-mocknet-standalone
    - cd ..
  script:
    - make build
    - make smoke
  after_script:
    - ./thornode/scripts/docker_logs.sh
