apiVersion: batch/v1
kind: Job
metadata:
  name: health
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: heimdall
        image: registry.gitlab.com/thorchain/heimdall
        imagePullPolicy: Always
        env:
          - name: LOGLEVEL
            value: INFO
        command:
          - python
          - scripts/health_prod.py
          - --thorchain=http://thor-api:1317
          - --binance=https://testnet-dex-atlantic.binance.org/api/v1
          - --midgard=http://midgard:8080
      restartPolicy: Never
